## Load libraries
```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
```

## Load the data
```{r}
fish <- readr::read_csv("archive/fish.csv")
```

```{r}
insects <- readr::read_csv("archive/insects.csv")
```

```{r}
glimpse(fish)
```

## Clean the names
```{r}
fish <- fish %>% 
  janitor::clean_names()
```


```{r}
names(fish)
```

## Select the columns that we will use 
```{r}
new_fish <- fish %>% 
  select(-color_1, -color_2, -size, -lighting_type, -icon_filename, -critterpedia_filename, -furniture_filename, -internal_id, -unique_entry_id)
```

## Look at NAs in the data
```{r}
naniar::miss_var_summary(new_fish)
```

## Split morning and night
```{r}
new_fish %>% 
 
```










## To catch a fish with a sell value of 10000, where would be a good place to fish? What fish would you expect to catch?

```{r}
new_fish %>% 
  select(name, sell, where_how) %>% 
  filter(sell==10000)
```

## What is the relationship between the shadow size of a fish and its sell price?
```{r}
new_fish %>% 
  ggplot(aes(x=shadow, y=sell, fill = shadow)) + geom_col() 
```
## Fish App

```{r}
library(shiny)
library(shinydashboard)
```


```{r}
library(shiny)

ui <- fluidPage(
  titlePanel("Animal Crossing Fish Data"),
  helpText("This dataset comes from this spreadsheet, a comprehensive Item Catalog for Animal Crossing New Horizons (ACNH).")
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```











